//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailQueue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emailQueue : IComparable
    {
        public int ID { get; set; }
        public string EFrom { get; set; }
        public string ETo { get; set; }
        public string ESubject { get; set; }
        public string CC { get; set; }
        public string EBody { get; set; }
        public int EPriority { get; set; }
        public string EStatus { get; set; }
        public int Tries { get; set; }

        int IComparable.CompareTo(object obj)
        {
            return EPriority;
        }
    }
}
